/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	ColorModeType: "enum",
	AccentType: "enum",
	BlockStatusEnum: "enum",
	query:{
		publication:{
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicOnly:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		publicationFeed:{
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicOnly:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		publicationContributors:{
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributor:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		contributorsByAddress:{
			addresses:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			}
		},
		entry:{
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		entries:{
			publicOnly:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		resolveENS:{
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		lookupENS:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		addressInfo:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		publicationSettings:{
			publicationLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifiedAccount:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		isVerified:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifiedAccountsAfterTimestamp:{
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		registrationEvent:{
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		votingPower:{
			account:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifiedVotesByRound:{
			round:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		crowdfunds:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		droppedCrowdfunds:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		crowdfundAtAddress:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		crowdfundBlockData:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		crowdfundEntries:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		nfts:{
			contributorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		nft:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		reserveAuctions:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		reserveAuction:{
			nftAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			auctionId:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		socialProfile:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		twitterProfile:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		twitterProfilesById:{
			ids:{
				type:"Int",
				array:true,
				arrayRequired:false,
				required:false
			}
		},
		splits:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		split:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		editions:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		edition:{
			editionId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			editionContractAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		userActivityFeed:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		email:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		crowdfundEvents:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		userProfile:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		me:{
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifyPublicKey:{
			publicKey:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		address:{
			publicKey:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mirrorProject:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		hasUserSubmittedSurvey:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			surveyId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		getSurvey:{
			surveyId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		crowdfundDraftById:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		proposals:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		proposal:{
			cid:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		proposalVotingPower:{
			cid:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		proposalEntryVotes:{
			proposalCid:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			proposalEntryCid:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		writeRaceSearch:{
			usernameOrAccount:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			roundNumber:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		writeRaceVotingPower:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			roundNumber:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		writeRaceCurrentUser:{
			account:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			roundNumber:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		writeRaceCurrentRound:{
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		writeRaceLeaderboard:{
			round:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mirrorPoll:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mirrorPollCanRespond:{
			pollId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mirrorPollUser:{
			pollId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		dutchAuction:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		editionOpenSale:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mirrorERC20Tokens:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mirrorERC20TokenAtAddress:{
			tokenAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		crowdfundTokenApprovalMetadata:{
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		projectFeed:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		plugins:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	VerificationStatusEnum: "enum",
	MirrorPollStatusEnum: "enum",
	DutchAuctionStatusType: "enum",
	mutations:{
		registerContributor:{
			contributorEthAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicationDisplayName:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicationENSLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicationAvatarURL:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorDisplayName:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorAvatarURL:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signingKey:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ethSignature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		registerContributorForPublication:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			displayName:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			avatarURL:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signingKey:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ethSignature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateContributorSettings:{
			contributorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			settings:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		removeContributor:{
			contributorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contractAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		changeEntryStatus:{
			originalDigest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			status:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createEntry:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			title:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			body:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			status:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			nftId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			entryContributorAddresses:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			featuredImageId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			hideTitleInEntry:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		addSigningKey:{
			ethAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicKey:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		addNonMemberSigningKey:{
			ethAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicKey:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		_testSigning:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateEntry:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			originalDigest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			title:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			body:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			status:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			nftId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			entryContributorAddresses:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			featuredImageId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			hideTitleInEntry:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateSettings:{
			publicationLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicationDisplayName:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publicationAvatarURL:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorDisplayName:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorAvatarURL:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updatePublicationSettings:{
			publicationLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			settings:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifyTweet:{
			tweetId:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			account:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifyTweetV2:{
			username:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			account:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		removeTwitter:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		saveRegistrationEvent:{
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			account:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifyVote:{
			candidate:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			round:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			account:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			amount:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createCrowdfund:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			symbol:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			description:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			baseURI:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publishStatus:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundingRecipient:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			goal:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			stretchGoal:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			endsAt:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			version:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributionLimit:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			operator:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			operatorEquityPercent:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			editions:{
				type:"EditionForSignatureType",
				array:true,
				arrayRequired:false,
				required:false
			},
			crowdfundDraftId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			content:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			metadata:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			title:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			exchangeRate:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setCrowdfundTransactionHash:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateCrowdfund:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			content:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateCrowdfundPublishStatus:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			publishStatus:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createNFT:{
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenURI:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contentHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			entryDigest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createReserveAuction:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			duration:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			nftAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundsRecipientAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			curatorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			curatorFee:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			version:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			reservePrice:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			auctionId:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createPromptResponse:{
			content:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			respondentId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contentHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createSplit:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createSplitAllocations:{
			splitAllocations:{
				type:"SplitAllocationInputType",
				array:true,
				arrayRequired:false,
				required:false
			}
		},
		createEdition:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			title:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			quantity:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			price:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			},
			artifactThumbnailId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			artifactPrimaryId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundingRecipient:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			description:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			editionContractAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			version:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			singleArtifact:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contentHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			baseUriHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createCrowdfundEditions:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			editions:{
				type:"EditionInputType",
				array:true,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundingRecipient:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			editionContractAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			version:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createEntryEditions:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			editions:{
				type:"EditionInputType",
				array:true,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundingRecipient:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			editionContractAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			version:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			entryId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setEditionTransactionHash:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ids:{
				type:"Int",
				array:true,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundingRecipient:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setEditionTransactionHashWithUserProfile:{
			ids:{
				type:"Int",
				array:true,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundingRecipient:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createMediaAsset:{
			mimetype:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sizes:{
				type:"MediaAssetSizesInputType",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		addEmail:{
			email:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		verifyEmail:{
			token:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setWriteRaceNotification:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			value:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createUserProfile:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			displayName:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			avatarURL:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateUserProfile:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			settings:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateUserProfileTheme:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			colorMode:{
				type:"ColorModeType",
				array:false,
				arrayRequired:false,
				required:false
			},
			accent:{
				type:"AccentType",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		relinkEns:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setUserProfileHeaderImage:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			headerImageId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		addSurveyResponse:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			content:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			surveyId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			contentHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createCrowdfundDraft:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			data:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		editCrowdfundDraft:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			data:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		deleteCrowdfundDraft:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createOrUpdateCrowdfundDraft:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			data:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setCrowdfundIdForCrowdfundDraft:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createProposal:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			title:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			description:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			erc20Address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			erc721Address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenIds:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			coverImageId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenThreshold:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			},
			startDate:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			endDate:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			prompt:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			highlightedWinners:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			entries:{
				type:"ProposalEntryInput",
				array:true,
				arrayRequired:false,
				required:false
			},
			erc721Multiplier:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		cancelProposal:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			cid:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		voteOnProposal:{
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			proposalCid:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			proposalEntryCid:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			votes:{
				type:"Float",
				array:false,
				arrayRequired:false,
				required:false
			},
			multisigAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		addMultisig:{
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			multisigAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contentHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		mirrorPollResponse:{
			pollId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			choiceId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			address:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createMirrorERC20Token:{
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			symbol:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			numDecimals:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			totalSupply:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			description:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			tokenAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			version:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			operatorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ensLabel:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			iconMediaAssetId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			nonce:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setMirrorERC20TokenTransactionHash:{
			tokenAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createEditionsOpenSale:{
			h:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contractAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userProfileId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			token:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			startTokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			endTokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			operator:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			recipient:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			price:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			open:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createCrowdfundTokenApproval:{
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			approvalAmount:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setTransactionHashForCrowdfundTokenApproval:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			crowdfundAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		createDutchAuction:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			name:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			description:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			subheading:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			editionContractAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			dutchAuctionAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			fundsRecipientAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			version:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			network:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			startTokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			endTokenId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			pricesInEth:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			interval:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setDutchAuctionTransactionHash:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			dutchAuctionAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			transactionHash:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		inviteProjectContributor:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		acceptProjectContributorInvite:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		revokeProjectContributor:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			contributorAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateProject:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			settings:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		setProjectHeaderImage:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			headerImageId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updateProjectTheme:{
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			colorMode:{
				type:"ColorModeType",
				array:false,
				arrayRequired:false,
				required:false
			},
			accent:{
				type:"AccentType",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		updatePluginStatus:{
			userAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			projectAddress:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			digest:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			signature:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			timestamp:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			pluginId:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			install:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	EditionForSignatureType:{
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		quantity:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		price:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		contentHash:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SplitAllocationInputType:{
		splitId:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		address:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		scaledPercent:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	EditionInputType:{
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		quantity:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		price:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		contentHash:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		artifactPrimaryId:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		artifactThumbnailId:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		singleArtifact:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		attributes:{
			type:"EditionAttributeInputType",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	EditionAttributeInputType:{
		trait_type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		display_type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		value:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	MediaAssetSizesInputType:{
		og:{
			type:"MediaAssetSizeInputType",
			array:false,
			arrayRequired:false,
			required:false
		},
		lg:{
			type:"MediaAssetSizeInputType",
			array:false,
			arrayRequired:false,
			required:false
		},
		md:{
			type:"MediaAssetSizeInputType",
			array:false,
			arrayRequired:false,
			required:false
		},
		sm:{
			type:"MediaAssetSizeInputType",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	MediaAssetSizeInputType:{
		height:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		width:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		src:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		size:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProposalEntryInput:{
		body:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		address:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitterUsername:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	publication:{
		id:"Int",
		ensLabel:"String",
		displayName:"String",
		avatarURL:"String",
		entries:"entry",
		crowdfundEntries:"crowdfund",
		posts:"PostType",
		publicationSettings:"publicationSettings",
		contributors:"contributor",
		nft:"nft"
	},
	crowdfund:{
		_id:"String",
		id:"Int",
		crowdfundDraftId:"Int",
		name:"String",
		symbol:"String",
		title:"String",
		contributorAddress:"String",
		description:"String",
		content:"String",
		publication:"publication",
		operator:"UserProfileType",
		address:"String",
		fundingRecipient:"String",
		goal:"String",
		stretchGoal:"String",
		network:"String",
		transactionHash:"String",
		contributionLimit:"String",
		endsAt:"Int",
		version:"String",
		editions:"edition",
		metadata:"CrowdfundMetadataType",
		publishStatus:"String",
		createdAt:"String",
		blockState:"BlockStateType",
		exchangeRate:"String",
		token:"mirrorERC20Token",
		publisher:"PublisherType"
	},
	UserProfileType:{
		address:"String",
		displayName:"String",
		avatarURL:"String",
		contributor:"contributor",
		nfts:"NFTType",
		editions:"EditionsType",
		notificationSettings:"NotificationSettingsType",
		theme:"UserProfileThemeType",
		ens:"String",
		headerImage:"MediaAssetType",
		description:"String",
		gaTrackingID:"String",
		mailingListURL:"String",
		domain:"String",
		memberships:"ProjectType",
		members:"ProjectType"
	},
	contributor:{
		address:"String",
		id:"String",
		displayName:"String",
		avatarURL:"String",
		publications:"publication",
		signingKeys:"signingKey"
	},
	signingKey:{
		id:"Int",
		publicKey:"String",
		signature:"signingKeySignature"
	},
	signingKeySignature:{
		id:"Int",
		signingKeyId:"Int",
		signature:"String",
		message:"String"
	},
	NFTType:{
		contract:"NFTContractType",
		name:"String",
		tokenId:"String",
		imageURL:"String",
		imagePreviewUrl:"String",
		imageThumbnailUrl:"String",
		imageOriginalUrl:"String",
		animationUrl:"String",
		animationOriginalUrl:"String"
	},
	NFTContractType:{
		address:"String",
		name:"String",
		symbol:"String"
	},
	EditionsType:{
		purchased:"EditionPurchasedType"
	},
	EditionPurchasedType:{
		blockNumber:"Int",
		transactionHash:"String",
		logIndex:"Int",
		event:"String",
		editionId:"String",
		tokenId:"String",
		numSold:"String",
		serial:"String",
		amountPaid:"String",
		buyer:"String",
		edition:"edition"
	},
	edition:{
		_id:"String",
		id:"Int",
		title:"String",
		quantity:"Int",
		description:"String",
		price:"Float",
		allocation:"Int",
		editionId:"Int",
		entryId:"Int",
		contentHash:"String",
		fundingRecipient:"String",
		transactionHash:"String",
		editionContractAddress:"String",
		version:"String",
		singleArtifact:"Boolean",
		attributes:"EditionAttribute",
		crowdfund:"crowdfund",
		primaryMedia:"MediaAssetType",
		thumbnailMedia:"MediaAssetType",
		mediaURL:"String",
		artifacts:"editionArtifact",
		operator:"UserProfileType",
		creator:"contributor",
		publication:"publication",
		entry:"entry",
		events:"EditionEventsType",
		tokenIds:"String",
		publisher:"PublisherType",
		blockState:"BlockStateType"
	},
	EditionAttribute:{
		trait_type:"String",
		display_type:"String",
		value:"String"
	},
	MediaAssetType:{
		id:"Int",
		mimetype:"String",
		sizes:"MediaAssetSizesType",
		url:"String"
	},
	MediaAssetSizesType:{
		og:"MediaAssetSizeType",
		lg:"MediaAssetSizeType",
		md:"MediaAssetSizeType",
		sm:"MediaAssetSizeType"
	},
	MediaAssetSizeType:{
		height:"Int",
		width:"Int",
		src:"String"
	},
	editionArtifact:{
		tokenId:"Int",
		editionId:"Int",
		url:"String"
	},
	EditionEventsType:{
		event:"String",
		blockNumber:"Int",
		logIndex:"Int",
		transactionHash:"String",
		network:"String",
		quantity:"String",
		price:"String",
		fundingRecipient:"String",
		editionId:"String",
		tokenId:"String",
		numSold:"String",
		buyer:"String",
		feePercent:"String",
		sender:"String",
		newFee:"String",
		feesAccrued:"String",
		previousOwner:"String",
		newOwner:"String",
		amountWithdrawn:"String",
		feeAmount:"String",
		amountPaid:"String",
		contentHash:"String",
		receiver:"String",
		previousCreator:"String",
		newCreator:"String",
		from:"String",
		to:"String",
		owner:"String",
		approved:"String",
		operator:"String",
		avatarURL:"String",
		twitterUsername:"String",
		collectorAddress:"String",
		serialNumber:"String"
	},
	PublisherType:{
		project:"ProjectType",
		member:"ProjectType"
	},
	ProjectType:{
		_id:"String",
		address:"String",
		displayName:"String",
		avatarURL:"String",
		notificationSettings:"NotificationSettingsType",
		theme:"UserProfileThemeType",
		ens:"String",
		headerImage:"MediaAssetType",
		description:"String",
		gaTrackingID:"String",
		mailingListURL:"String",
		domain:"String",
		memberships:"ProjectType",
		members:"ProjectType",
		pendingMemberships:"ProjectType",
		pendingMembers:"ProjectType",
		posts:"PostType",
		featureFlags:"FeatureFlagStatusType",
		navigation:"NavigationType"
	},
	NotificationSettingsType:{
		writeRace:"Boolean"
	},
	UserProfileThemeType:{
		colorMode:"ColorModeType",
		accent:"AccentType"
	},
	PostType:{
		"...on entry":"entry",
		"...on crowdfund":"crowdfund"
	},
	FeatureFlagStatusType:{
		isPluginsTabEnabled:"Boolean"
	},
	NavigationType:{
		section:"NavigationSectionType",
		content:"NavigationContentType"
	},
	NavigationSectionType:{
		isFundingEnabled:"Boolean",
		isNFTsEnabled:"Boolean",
		isGovernanceEnabled:"Boolean"
	},
	NavigationContentType:{
		isCrowdfundsEnabled:"Boolean",
		isSplitsEnabled:"Boolean",
		isTokensEnabled:"Boolean",
		isEditionsEnabled:"Boolean",
		isTokenRaceEnabled:"Boolean",
		isAuctionsEnabled:"Boolean"
	},
	BlockStateType:{
		status:"BlockStatusEnum"
	},
	CrowdfundMetadataType:{
		coverImage:"MediaAssetType",
		podium:"PodiumType"
	},
	PodiumType:{
		first:"PodiumFieldType",
		second:"PodiumFieldType",
		third:"PodiumFieldType",
		duration:"Int"
	},
	PodiumFieldType:{
		title:"String",
		description:"String",
		primaryMedia:"MediaAssetType",
		thumbnailMedia:"MediaAssetType"
	},
	mirrorERC20Token:{
		id:"Int",
		name:"String",
		symbol:"String",
		numDecimals:"String",
		totalSupply:"String",
		totalSupplyFormatted:"String",
		operator:"UserProfileType",
		description:"String",
		publication:"publication",
		tokenAddress:"String",
		iconMedia:"MediaAssetType",
		network:"String",
		transactionHash:"String",
		contributionLimit:"String",
		ownerAddress:"String",
		version:"String",
		createdAt:"String",
		publisher:"PublisherType"
	},
	publicationSettings:{
		publicationLabel:"String",
		settings:"String",
		digest:"String",
		contributorAddress:"String",
		key:"String",
		signature:"String",
		timestamp:"Int"
	},
	nft:{
		id:"Int",
		name:"String",
		tokenURI:"String",
		contributorAddress:"String",
		address:"String",
		contentHash:"String",
		network:"String",
		tokenId:"Int",
		transactionHash:"String",
		entryDigest:"String"
	},
	entry:{
		_id:"String",
		id:"Int",
		entryId:"Int",
		digest:"String",
		originalDigest:"String",
		title:"String",
		hideTitleInEntry:"Boolean",
		body:"String",
		timestamp:"Int",
		publishedAtTimestamp:"Int",
		publishStatus:"String",
		canonicalUrl:"String",
		publicationId:"Int",
		userProfileId:"Int",
		featuredImageId:"Int",
		arweaveTransactionRequest:"ArweaveTransactionRequestType",
		nftTransactionHash:"String",
		nftAddress:"Int",
		nftTokenId:"Int",
		publication:"publication",
		userProfile:"UserProfileType",
		contributor:"contributor",
		author:"UserProfileType",
		nft:"nft",
		authorship:"Authorship",
		contributors:"contributor",
		editions:"edition",
		featuredImage:"MediaAssetType",
		publisher:"PublisherType",
		collaborators:"ProjectType"
	},
	ArweaveTransactionRequestType:{
		id:"Int",
		transactionId:"String",
		entryId:"Int"
	},
	Authorship:{
		publicKey:"String",
		signature:"String"
	},
	query:{
		publication:"publication",
		publicationFeed:"publication",
		publicationContributors:"contributor",
		publications:"publication",
		contributor:"contributor",
		contributorsByAddress:"contributor",
		nextContributorId:"Int",
		entry:"entry",
		entries:"entry",
		resolveENS:"ENS",
		lookupENS:"ENS",
		addressInfo:"addressInfo",
		publicationSettings:"publicationSettings",
		verifiedAccounts:"VerifiedAccount",
		verifiedAccount:"VerifiedAccount",
		isVerified:"Boolean",
		verifiedAccountsAfterTimestamp:"VerifiedAccount",
		registrationEvent:"registrationEvent",
		registrationEvents:"registrationEvent",
		registeredProfiles:"RegisteredProfile",
		verifiedVotes:"VerifiedVoteType",
		votingPower:"VotingPowerType",
		verifiedVotesByRound:"VerifiedVoteType",
		crowdfunds:"CrowdfundListType",
		droppedCrowdfunds:"crowdfund",
		crowdfundAtAddress:"crowdfund",
		crowdfundBlockData:"CrowdfundBlock",
		crowdfundEntries:"crowdfund",
		nfts:"nft",
		nft:"nft",
		reserveAuctions:"reserveAuction",
		reserveAuction:"reserveAuction",
		socialProfiles:"SocialProfileType",
		socialProfile:"SocialProfileType",
		writeRaceProfiles:"WriteRaceProfileType",
		leaderboard:"LeaderboardType",
		twitterProfile:"TwitterProfileType",
		twitterProfilesById:"TwitterProfileType",
		splits:"SplitType",
		split:"SplitType",
		unverifiedTwitterProfiles:"UnverifiedTwitterProfileType",
		editions:"edition",
		edition:"edition",
		userActivityFeed:"ActivityPropertiesType",
		email:"email",
		crowdfundEvents:"crowdfundEvents",
		userProfile:"UserProfileType",
		me:"ProjectType",
		verifyPublicKey:"PublicKeyVerification",
		address:"String",
		mirrorProject:"MirrorProjectType",
		projectThemeOptions:"ProjectThemeOptionsType",
		hasUserSubmittedSurvey:"Boolean",
		getSurvey:"SurveyType",
		crowdfundDraftById:"CrowdfundDraft",
		contracts:"Contract",
		proposals:"Proposal",
		proposal:"Proposal",
		proposalVotingPower:"ProposalUserVotingPower",
		proposalEntryVotes:"ProposalEntryVote",
		writeRaceSearch:"WriteRaceRoundDataType",
		writeRaceVotingPower:"WriteRaceVotingPowerType",
		writeRaceCurrentUser:"WriteRaceCurrentUser",
		writeRaceCurrentRound:"WriteRaceCurrentRound",
		writeRaceLeaderboard:"WriteRaceLeaderboardType",
		writeRaceGenesisWriters:"WriteRaceLeaderboardWinnerType",
		mirrorPoll:"MirrorPollType",
		mirrorPollCanRespond:"Boolean",
		mirrorPollUser:"MirrorPollUser",
		dutchAuction:"DutchAuctionType",
		editionOpenSale:"editionOpenSale",
		mirrorERC20Tokens:"mirrorERC20Token",
		mirrorERC20TokenAtAddress:"mirrorERC20Token",
		crowdfundTokenApprovalMetadata:"crowdfundTokenApprovalMetadata",
		projectFeed:"ProjectType",
		plugins:"PluginType",
		pluginsList:"PluginType"
	},
	ENS:{
		name:"String",
		address:"String"
	},
	addressInfo:{
		ens:"String",
		writeTokens:"String",
		hasOnboarded:"Boolean"
	},
	VerifiedAccount:{
		twitterProfileId:"Int",
		account:"String",
		username:"String",
		signature:"String",
		name:"String",
		twitterId:"String",
		avatarURL:"String",
		followerCount:"Int",
		promptResponse:"promptResponse"
	},
	promptResponse:{
		id:"Int",
		content:"String",
		createdAt:"String"
	},
	registrationEvent:{
		id:"Int",
		account:"String",
		ensLabel:"String",
		transactionHash:"String"
	},
	RegisteredProfile:{
		id:"Int",
		account:"String",
		username:"String",
		avatarURL:"String"
	},
	VerifiedVoteType:{
		account:"String",
		candidate:"String",
		round:"String",
		signature:"String",
		amount:"Int",
		createdAt:"Int"
	},
	VotingPowerType:{
		account:"String",
		votingPower:"Float",
		round:"String",
		reasons:"String"
	},
	CrowdfundListType:{
		"...on CrowdfundDraft":"CrowdfundDraft",
		"...on crowdfund":"crowdfund"
	},
	CrowdfundDraft:{
		_id:"String",
		id:"Int",
		data:"String",
		name:"String",
		symbol:"String",
		title:"String",
		crowdfundDraftId:"Int",
		publisher:"PublisherType"
	},
	CrowdfundBlock:{
		name:"String",
		symbol:"String",
		contractAddress:"String",
		valueCurrent:"String",
		stretchGoal:"Float",
		fundingCap:"Float",
		tokensIssued:"String",
		isRedeemable:"Boolean",
		isActive:"Boolean",
		operatorEquityPercent:"String",
		contributionLimit:"String",
		fundingRecipientAddress:"String",
		operator:"UserProfileType",
		backers:"CrowdfundBacker",
		events:"CrowdfundEvent",
		podiumDuration:"Int",
		podiumStartTime:"Int",
		minPodiumBid:"String",
		accountBalance:"String",
		totalSupply:"String",
		status:"String"
	},
	CrowdfundBacker:{
		eth:"String",
		tokens:"String",
		address:"String",
		blockNumber:"Int",
		avatarURL:"String",
		twitterUsername:"String",
		percentage:"String"
	},
	CrowdfundEvent:{
		id:"Int",
		event:"String",
		amount:"String",
		amountRaised:"String",
		amountFormatted:"Float",
		amountRaisedFormatted:"String",
		creatorAllocation:"String",
		value:"String",
		address:"String",
		from:"String",
		to:"String",
		blockNumber:"Int",
		logIndex:"Int",
		network:"String",
		transactionHash:"String",
		editionId:"Int",
		tokenId:"Int",
		crowdfundId:"Int",
		timestamp:"String"
	},
	reserveAuction:{
		_id:"String",
		id:"Int",
		tokenId:"Int",
		duration:"Int",
		address:"String",
		nftAddress:"String",
		auctionId:"String",
		creatorShareRecipientAddress:"String",
		creatorAddress:"String",
		fundsRecipientAddress:"String",
		deployerAddress:"String",
		curatorAddress:"String",
		curatorFee:"String",
		version:"String",
		reservePrice:"String",
		network:"String",
		transactionHash:"String",
		createdAt:"String",
		events:"ReserveAuctionEvent",
		operator:"UserProfileType",
		deployer:"contributor",
		publication:"publication",
		publisher:"PublisherType"
	},
	ReserveAuctionEvent:{
		event:"String",
		blockNumber:"Int",
		logIndex:"Int",
		transactionHash:"String",
		network:"String",
		nftContractAddress:"String",
		tokenId:"String",
		curator:"String",
		amount:"String",
		winner:"String",
		nftCreator:"String",
		fundsRecipient:"String",
		value:"String",
		sender:"String",
		duration:"String",
		reservePrice:"String",
		curatorFeePercent:"String",
		creator:"String",
		originalCreator:"String",
		zoraAddress:"String",
		creatorShareRecipient:"String",
		firstBid:"String",
		extended:"String",
		timestamp:"String",
		auctionId:"String"
	},
	SocialProfileType:{
		address:"String",
		twitter:"TwitterProfileType",
		mirror:"MirrorProfileType"
	},
	TwitterProfileType:{
		id:"Int",
		username:"String",
		avatarURL:"String",
		twitterId:"String",
		followerCount:"Int",
		name:"String"
	},
	MirrorProfileType:{
		contributor:"contributor"
	},
	WriteRaceProfileType:{
		address:"String",
		twitter:"TwitterProfileType",
		mirror:"MirrorProfileType",
		promptResponse:"promptResponse"
	},
	LeaderboardType:{
		title:"String",
		numVotes:"Int",
		candidates:"Int",
		profiles:"LeaderboardProfileType"
	},
	LeaderboardProfileType:{
		numVotes:"Int",
		votingPower:"Int",
		account:"String",
		username:"String",
		avatarURL:"String",
		followerCount:"Int",
		backers:"LeaderboardBackerType",
		ensDomain:"String",
		notHighlighted:"Boolean"
	},
	LeaderboardBackerType:{
		amount:"Int",
		account:"String",
		username:"String",
		avatarURL:"String",
		followerCount:"Int"
	},
	SplitType:{
		_id:"String",
		id:"Int",
		name:"String",
		address:"String",
		transactionHash:"String",
		network:"String",
		splitAllocations:"SplitAllocationType",
		events:"SplitEventType",
		operator:"UserProfileType",
		publication:"publication",
		publisher:"PublisherType"
	},
	SplitAllocationType:{
		id:"Int",
		address:"String",
		scaledPercent:"Int",
		splitAmount:"Float",
		account:"String",
		userProfile:"UserProfileType"
	},
	SplitEventType:{
		event:"String",
		account:"String",
		amount:"String",
		amountFormatted:"String",
		asset:"String",
		blockNumber:"Int",
		category:"String",
		currentWindow:"String",
		from:"String",
		fundsAvailable:"String",
		fundsAvailableFormatted:"String",
		logIndex:"Int",
		network:"String",
		success:"String",
		to:"String",
		transactionHash:"String"
	},
	UnverifiedTwitterProfileType:{
		id:"Int",
		address:"String",
		twitterProfile:"TwitterProfileType"
	},
	ActivityPropertiesType:{
		key:"String",
		detailValue:"String"
	},
	email:{
		verificationStatus:"VerificationStatusEnum"
	},
	crowdfundEvents:{
		event:"String",
		amount:"String",
		amountRaised:"String",
		amountFormatted:"Float",
		amountRaisedFormatted:"Float",
		creatorAllocation:"String",
		value:"String",
		address:"String",
		from:"String",
		to:"String",
		blockNumber:"Int",
		logIndex:"Int",
		network:"String",
		transactionHash:"String",
		tokenId:"String",
		editionId:"String"
	},
	PublicKeyVerification:{
		address:"String"
	},
	MirrorProjectType:{
		isRegistered:"Boolean",
		projectDetails:"ProjectType"
	},
	ProjectThemeOptionsType:{
		colorModes:"String",
		accents:"String"
	},
	SurveyType:{
		prompt:"String",
		backers:"String",
		title:"String",
		description:"String"
	},
	Contract:{
		name:"String",
		abi:"String",
		address:"String",
		version:"String"
	},
	Proposal:{
		_id:"String",
		cid:"String",
		erc20Address:"String",
		erc721Address:"String",
		startDate:"String",
		endDate:"String",
		tokenName:"String",
		tokenSymbol:"String",
		title:"String",
		description:"String",
		prompt:"String",
		tokenThreshold:"Float",
		tokenIds:"String",
		highlightedWinners:"Int",
		coverImage:"MediaAssetType",
		status:"String",
		snapshot:"ProposalSnapshot",
		results:"ProposalResult",
		resultsCid:"String",
		entries:"ProposalEntry",
		operator:"UserProfileType",
		publication:"publication",
		erc721Multiplier:"Int",
		publisher:"PublisherType"
	},
	ProposalSnapshot:{
		cid:"String",
		blockNumber:"String"
	},
	ProposalResult:{
		votes:"Float",
		proposalEntryCid:"String",
		proposalCid:"String",
		body:"String",
		entryAuthorAddress:"String",
		isHighlighted:"Boolean",
		position:"Int"
	},
	ProposalEntry:{
		address:"String",
		body:"String",
		cid:"String",
		proposalCid:"String",
		votes:"Float",
		twitter:"TwitterProfileType"
	},
	ProposalUserVotingPower:{
		totalVotes:"Float",
		availableVotes:"Float",
		multisigs:"ProposalVotingPowerMultisig"
	},
	ProposalVotingPowerMultisig:{
		totalVotes:"Float",
		availableVotes:"Float",
		address:"String"
	},
	ProposalEntryVote:{
		votes:"Float",
		address:"String",
		twitter:"TwitterProfileType"
	},
	WriteRaceRoundDataType:{
		address:"String",
		votes:"Int",
		voters:"WriteRaceVoterDataType",
		twitter:"TwitterProfileType",
		response:"String",
		score:"Float"
	},
	WriteRaceVoterDataType:{
		address:"String",
		twitter:"TwitterProfileType",
		votes:"Int"
	},
	WriteRaceVotingPowerType:{
		totalVotes:"Int",
		availableVotes:"Int"
	},
	WriteRaceCurrentUser:{
		address:"String",
		votes:"Int",
		voters:"WriteRaceVoterDataType",
		twitter:"TwitterProfileType",
		response:"String",
		isRegistered:"Boolean",
		isWinner:"Boolean",
		rank:"Int"
	},
	WriteRaceCurrentRound:{
		round:"Int",
		status:"String",
		startsAt:"String",
		endsAt:"String",
		roundDetails:"WriteRaceRoundType",
		isQuadratic:"Boolean",
		isPaused:"Boolean"
	},
	WriteRaceRoundType:{
		roundData:"WriteRaceRoundDataType",
		votesCast:"Int",
		candidates:"Int",
		currentPrompt:"String",
		roundNumber:"Int",
		voters:"Int"
	},
	WriteRaceLeaderboardType:{
		isQuadratic:"Boolean",
		votes:"Int",
		candidates:"Int",
		winners:"WriteRaceLeaderboardWinnerType",
		voters:"Int"
	},
	WriteRaceLeaderboardWinnerType:{
		voters:"WriteRaceVoterDataType",
		address:"String",
		votes:"Int",
		score:"Float",
		votingPower:"Int",
		twitter:"TwitterProfileType",
		ensLabel:"String"
	},
	MirrorPollType:{
		_id:"String",
		id:"Int",
		title:"String",
		description:"String",
		prompt:"String",
		status:"MirrorPollStatusEnum",
		endsAt:"String",
		startsAt:"String",
		coverImage:"MediaAssetType",
		choices:"MirrorPollChoice"
	},
	MirrorPollChoice:{
		id:"Int",
		title:"String",
		description:"String",
		responses:"MirrorPollResponse"
	},
	MirrorPollResponse:{
		address:"String",
		twitter:"TwitterProfileType"
	},
	MirrorPollUser:{
		hasPermission:"Boolean",
		existingVote:"Int"
	},
	DutchAuctionType:{
		_id:"String",
		events:"DutchAuctionEventType",
		status:"DutchAuctionStatusType",
		operator:"UserProfileType",
		publication:"publication",
		address:"String",
		transactionHash:"String",
		version:"String",
		fundsRecipientAddress:"String",
		name:"String",
		subheading:"String",
		description:"String",
		tokenIds:"Int",
		prices:"Float",
		totalSupply:"Int",
		collected:"Int",
		currentPrice:"Float",
		timeRemaining:"String",
		nextBlock:"String",
		edition:"edition",
		isPaused:"Boolean",
		collectors:"CollectorType",
		totalRaised:"Float",
		hasStarted:"Boolean",
		network:"String",
		publisher:"PublisherType"
	},
	DutchAuctionEventType:{
		blockNumber:"Int",
		logIndex:"Int",
		network:"String",
		transactionHash:"String",
		event:"String",
		tokenId:"String",
		recipient:"String",
		amount:"String",
		fee:"String",
		price:"String",
		account:"String",
		priceFormatted:"String",
		amountFormatted:"String",
		feeFormatted:"String"
	},
	CollectorType:{
		address:"String",
		user:"UserProfileType",
		price:"Float"
	},
	editionOpenSale:{
		id:"Int",
		token:"String",
		operator:"String",
		recipient:"String",
		symbol:"String",
		startTokenId:"String",
		endTokenId:"String",
		price:"String",
		userProfile:"UserProfileType",
		publication:"publication",
		contract:"Contract",
		h:"String",
		network:"String",
		transactionHash:"String",
		contributionLimit:"String",
		version:"String",
		createdAt:"String",
		open:"Boolean",
		status:"String",
		publisher:"PublisherType",
		purchases:"editionOpenSalePurchase"
	},
	editionOpenSalePurchase:{
		tokenId:"Int",
		buyer:"String",
		recipient:"String",
		twitterUsername:"String",
		avatarURL:"String",
		transactionHash:"String"
	},
	crowdfundTokenApprovalMetadata:{
		id:"Int",
		status:"String",
		tokenAddress:"String",
		crowdfundAddress:"String",
		numberOfTokensToApprove:"String",
		tokenOwnerAddress:"String",
		transactionHash:"String"
	},
	PluginType:{
		_id:"Int",
		key:"String",
		name:"String",
		description:"String",
		category:"String",
		imageURL:"String",
		installed:"Boolean"
	},
	mutations:{
		registerContributor:"contributor",
		registerContributorForPublication:"contributor",
		updateContributorSettings:"contributor",
		removeContributor:"success",
		changeEntryStatus:"Boolean",
		createEntry:"entry",
		addSigningKey:"signingKey",
		addNonMemberSigningKey:"signingKey",
		_testSigning:"Boolean",
		updateEntry:"entry",
		updateSettings:"Boolean",
		updatePublicationSettings:"publicationSettings",
		verifyTweet:"Boolean",
		verifyTweetV2:"Boolean",
		removeTwitter:"Boolean",
		saveRegistrationEvent:"registrationEvent",
		verifyVote:"Boolean",
		createCrowdfund:"crowdfund",
		setCrowdfundTransactionHash:"Boolean",
		updateCrowdfund:"crowdfund",
		updateCrowdfundPublishStatus:"crowdfund",
		createNFT:"nft",
		createReserveAuction:"reserveAuction",
		createPromptResponse:"promptResponse",
		createSplit:"SplitType",
		createSplitAllocations:"Boolean",
		createEdition:"edition",
		createCrowdfundEditions:"edition",
		createEntryEditions:"edition",
		setEditionTransactionHash:"Boolean",
		setEditionTransactionHashWithUserProfile:"Boolean",
		createMediaAsset:"MediaAssetType",
		addEmail:"email",
		verifyEmail:"email",
		setWriteRaceNotification:"Boolean",
		createUserProfile:"UserProfileType",
		updateUserProfile:"UserProfileType",
		updateUserProfileTheme:"UserProfileThemeType",
		relinkEns:"ENS",
		setUserProfileHeaderImage:"MediaAssetType",
		addSurveyResponse:"Boolean",
		createCrowdfundDraft:"CrowdfundDraft",
		editCrowdfundDraft:"CrowdfundDraft",
		deleteCrowdfundDraft:"Boolean",
		createOrUpdateCrowdfundDraft:"CrowdfundDraft",
		setCrowdfundIdForCrowdfundDraft:"Boolean",
		createProposal:"Proposal",
		cancelProposal:"Boolean",
		voteOnProposal:"ProposalUserVotingPower",
		addMultisig:"Boolean",
		mirrorPollResponse:"Boolean",
		createMirrorERC20Token:"mirrorERC20Token",
		setMirrorERC20TokenTransactionHash:"Boolean",
		createEditionsOpenSale:"editionOpenSale",
		createCrowdfundTokenApproval:"Boolean",
		setTransactionHashForCrowdfundTokenApproval:"Boolean",
		createDutchAuction:"DutchAuctionType",
		setDutchAuctionTransactionHash:"Boolean",
		inviteProjectContributor:"ProjectType",
		acceptProjectContributorInvite:"ProjectType",
		revokeProjectContributor:"ProjectType",
		updateProject:"ProjectType",
		setProjectHeaderImage:"MediaAssetType",
		updateProjectTheme:"ProjectThemeType",
		updatePluginStatus:"PluginType"
	},
	success:{
		success:"Boolean"
	},
	ProjectThemeType:{
		colorMode:"ColorModeType",
		accent:"AccentType"
	}
}